#!/usr/bin/env bun
/**
 * Emit the canary v2 golden wire vectors under
 * `packages/core/src/canary/__golden__/`.
 *
 *   bun run scripts/generate-canary-golden-vectors.ts           # write
 *   bun run scripts/generate-canary-golden-vectors.ts --check   # verify
 *
 * `--check` is what CI runs: it fails if the committed files differ from what
 * the current code produces, so the published contract surface cannot drift
 * from the implementation without someone noticing.
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { createHash } from 'node:crypto';
import {
  GOLDEN_AUTHENTICATION,
  GOLDEN_ENDPOINTS,
  GOLDEN_OUTPUT_CONTRACT,
  GOLDEN_PRINCIPAL,
  GOLDEN_SENTINELS,
  GOLDEN_TERMINAL_VOCABULARY,
  goldenDigest,
  goldenPendingAcknowledgement,
  goldenRequest,
  goldenTerminalFailure,
  goldenTerminalSuccess,
} from '../packages/core/src/canary/golden-vectors';
import { CANARY_CONTRACT_VERSION } from '../packages/core/src/canary/contract';

const OUT_DIR = join(import.meta.dir, '..', 'packages', 'core', 'src', 'canary', '__golden__');

const NOTE =
  'Golden wire vector for the Archon bounded canary contract. Generated by ' +
  'scripts/generate-canary-golden-vectors.ts — do not hand-edit; run the ' +
  'generator and commit the result.';

/** Every vector carries the same header so a consumer can read one in isolation. */
function envelope(extra: Record<string, unknown>): Record<string, unknown> {
  return {
    $note: NOTE,
    contract_version: CANARY_CONTRACT_VERSION,
    principal: GOLDEN_PRINCIPAL,
    authentication: GOLDEN_AUTHENTICATION,
    volatile_field_sentinels: GOLDEN_SENTINELS,
    ...extra,
  };
}

export const GOLDEN_FILES: Record<string, unknown> = {
  'request.json': envelope({
    endpoint: GOLDEN_ENDPOINTS.submit,
    $description:
      'The submit body. There is deliberately no `principal` field — the ' +
      'principal is authority and is resolved from the bearer token; sending ' +
      'one is a 400 because the schema is strict.',
    contract_digest: goldenDigest(),
    $digest_definition:
      'sha256 over canonical JSON of {authenticated_principal, request}, keys sorted at every depth',
    request: goldenRequest(),
  }),

  'pending-acknowledgement.json': envelope({
    endpoint: GOLDEN_ENDPOINTS.submit,
    $description:
      'The 202 acknowledgement. NOT a settlement: state is "pending", every ' +
      'settleable field is ABSENT (not zero), and there is no output block at ' +
      'all — not even output_available:false, which would read as a settled ' +
      '"this produced nothing". Poll the read endpoint for the terminal receipt.',
    response: goldenPendingAcknowledgement(),
  }),

  'terminal-receipt-success.json': envelope({
    endpoint: GOLDEN_ENDPOINTS.read,
    $description:
      'A settled receipt for a run that completed, carrying its governed ' +
      'deliverable. terminal_status "succeeded" iff reason is "completed", and ' +
      'a succeeded receipt ALWAYS carries output_available:true — Archon fails ' +
      'the run closed rather than report success with nothing to show for it. ' +
      'Verify output_sha256 over the UTF-8 bytes of output_text before acting.',
    terminal_vocabulary: GOLDEN_TERMINAL_VOCABULARY,
    output_contract: GOLDEN_OUTPUT_CONTRACT,
    response: { receipt: goldenTerminalSuccess() },
  }),

  'terminal-receipt-failed.json': envelope({
    endpoint: GOLDEN_ENDPOINTS.read,
    $description:
      'A settled receipt for a run that hit its budget ceiling. The aggregate ' +
      'is present and must be settled from — a ceiling hit is a real, billed ' +
      'run, reported as failed because it did not do the work. ' +
      'output_available is false and output_text is ABSENT, not empty: a failed ' +
      'run publishes no deliverable even if the agent left partial text behind.',
    terminal_vocabulary: GOLDEN_TERMINAL_VOCABULARY,
    output_contract: GOLDEN_OUTPUT_CONTRACT,
    response: { receipt: goldenTerminalFailure() },
  }),
};

/** Stable 2-space JSON with a trailing newline, so diffs stay readable. */
function render(value: unknown): string {
  return `${JSON.stringify(value, null, 2)}\n`;
}

export function sha256(text: string): string {
  return createHash('sha256').update(text, 'utf8').digest('hex');
}

function main(): void {
  const check = process.argv.includes('--check');
  if (!check && !existsSync(OUT_DIR)) mkdirSync(OUT_DIR, { recursive: true });

  const stale: string[] = [];
  for (const [name, value] of Object.entries(GOLDEN_FILES)) {
    const path = join(OUT_DIR, name);
    const rendered = render(value);
    if (check) {
      const actual = existsSync(path) ? readFileSync(path, 'utf8') : '';
      if (actual !== rendered) stale.push(name);
    } else {
      writeFileSync(path, rendered);
      console.log(`${name}  sha256=${sha256(rendered)}`);
    }
  }

  if (check) {
    if (stale.length > 0) {
      console.error(
        `Canary golden vectors are stale: ${stale.join(', ')}\n` +
          'Run: bun run scripts/generate-canary-golden-vectors.ts'
      );
      process.exit(1);
    }
    console.log('check:canary-golden-vectors OK');
  }
}

if (import.meta.main) main();
